apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: business-application-service
  name: business-application-service
spec:
  replicas: 1
  selector:
    app: business-application-service
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: business-application-service
        namespace: ${NAMESPACE_TO_DEPLOY_TO}
    spec:
      containers:
      - name: ${NAMESPACE_TO_DEPLOY_TO}-business-application-service
        env:
        - name: GC_MAX_METASPACE_SIZE
          value: "512"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE_TO_BUILD_AT}/business-application-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange

